######################################################################
# Automatically generated by qmake (2.01a) niedz. gru 4 18:24:53 2011
######################################################################

QT -= core gui
CONFIG -= qt

LIBS += -lSDL -lSDL_image -lSDL_ttf

# Input
SOURCES += src/main.cpp \
    src/klocuchy.cpp

HEADERS += \
    src/klocuchy.h


