######################################################################
# Automatically generated by qmake (2.01a) niedz. gru 4 18:24:53 2011
######################################################################

QT -= core gui
CONFIG -= qt

OBJECTS_DIR = tmp

win32:LIBS += SDLmain
LIBS += -lSDL -lSDL_image -lSDL_ttf

# Input
SOURCES += src/main.cpp \
    src/klocuchy.cpp \
    src/gamedata.cpp \
    src/button.cpp \
    src/mainmenu.cpp \
    src/timer.cpp \
    src/tile.cpp \
    src/background.cpp \
    src/drawer.cpp \
    src/frame.cpp \
    src/tetramino.cpp \
    src/nextview.cpp \
    src/tetrion.cpp \
    src/scoreview.cpp

HEADERS += \
    src/klocuchy.h \
    src/gamedata.h \
    src/button.h \
    src/defines.h \
    src/mainmenu.h \
    src/timer.h \
    src/tile.h \
    src/background.h \
    src/drawer.h \
    src/frame.h \
    src/tetramino.h \
    src/nextview.h \
    src/tetrion.h \
    src/scoreview.h
<<<<<<< HEAD


=======
>>>>>>> ad1638b656ecf6267329f562abf77034a5493b2d

























